support NPM_TOKEN
reactioncommerce/docker-base pull request #29
Opened 2020-06-26 19:49 UTC by jhonsfran1165

close #28

2020-07-01 21:31 UTC, focusaurus approved these changes

2020-07-01 21:36 UTC, focusaurus requested changes
Changes themselves look good. Could you please leave this file unchanged but copy and modify the existing prod images so we end up with the following?

```
images/node-prod/10.16.3-v2/Dockerfile
images/node-prod/12.10.0-v2/Dockerfile
images/node-prod/12.14.1-v3/Dockerfile
```

2020-07-01 22:19 UTC, jhonsfran1165 commented
You got it @focusaurus

2020-07-02 15:17 UTC, focusaurus approved these changes

2020-07-02 15:17 UTC, merged